name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt pyinstaller

      - name: Build project
        run: pyinstaller --noconfirm build.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Polsu Overlay
          path: dist/Polsu Overlay.exe