name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Check version
        id: check_version
        shell: pwsh
        run: |
          $diff = git diff --name-only HEAD^ HEAD

          $SourceDiff = $diff | Where-Object { $_ -match "version.rc" }
          $HasDiff = $SourceDiff.Length -gt 0

          Write-Host "::set-output name=version_changed::$HasDiff"

      - name: Install dependencies
        run: pip install -r requirements.txt pyinstaller

      - name: Build project
        shell: pwsh
        run: |
          if [[ "${{ steps.check_version.outputs.version_changed }}" == "true" ]]; then
            pyinstaller --noconfirm build.spec
          else
            echo "Version is not changed. Skipping build."
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Polsu Overlay
          path: dist/Polsu Overlay.exe