name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Check version
        id: check_version
        run: |
          if ((git diff --name-only HEAD^ HEAD) -match 'version\.rc|__init__\.py') {
            echo "::set-output name=version_changed::true"
          } else {
            echo "::set-output name=version_changed::false"
          }

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build project
        run: |
          if ("${{ steps.check_version.outputs.version_changed }}" -eq "true") {
            pyinstaller --noconfirm build.spec
          } else {
            echo "Version is not changed. Skipping build."
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Polsu Overlay
          path: dist/Polsu Overlay.exe